function savefigs_column2(file, ht_cm)
% savefigs_column2(file, ht_cm)

if ht_cm > Fig.Consts.height_max_cm
    warning('ht_cm = %d is larger than the maximum height allowed!', ...
        ht_cm);
end

bml.plot.savefigs(file, ...
    'PaperPosition', [0, 0, ...
        Fig.Consts.width_column2_cm, ...
        ht_cm], ...
    'ext', {'.fig', '.png', '.tif'});
